Repository bcc-code/bcc-media-app, pull requests merged in 2023-02, with the labels that each got.

#64 Feat/live now badge
  lib/api/brunstadtv.dart
  lib/components/default_grid_section.dart
  lib/components/default_section.dart
  lib/components/featured_section.dart
  lib/components/page.dart
  lib/components/poster_grid_section.dart
  lib/components/poster_section.dart
  lib/graphql/queries/calendar_episode_entries.graphql
  lib/graphql/queries/calendar_episode_entries.graphql.dart
  lib/helpers/utils.dart
  lib/providers/auth_state.freezed.dart
  lib/providers/settings.freezed.dart
  lib/providers/todays_calendar_entries.dart
  lib/screens/calendar/calendar.dart
  lib/services/utils.dart
  pubspec.lock
Labels: codeball:needs-careful-review

#81 Webfix2
  .vscode/launch.json
  external_projects/bccm_player/example/pubspec.lock
  external_projects/bccm_player/lib/bccm_castplayer.dart
  external_projects/bccm_player/lib/bccm_player.dart
  external_projects/bccm_player/lib/bccm_player_web.dart
  external_projects/bccm_player/lib/cast_button.dart
  external_projects/bccm_player/lib/playback_listener.dart
  external_projects/bccm_player/lib/playback_service_interface.dart
  external_projects/bccm_player/lib/web/web_player.dart
  external_projects/bccm_player/pubspec.yaml
  integration_test/tests/login_test.dart
  lib/api/brunstadtv.dart
  lib/app_root.dart
  lib/components/custom_tab_bar.dart
  lib/components/developer_options.dart
  lib/components/error_no_access.dart
  lib/env/prod/firebase_options.dart
  lib/env/v4_prod/firebase_options.dart
  lib/generated_plugin_registrant.dart
  lib/graphql/client.dart
  lib/helpers/webview/main_js_channel.dart
  lib/main.dart
  lib/models/auth_state.dart
  lib/models/auth_state.freezed.dart
  lib/providers/auth_state/auth_state.dart
  lib/providers/auth_state/auth_state_notifier_stub.dart
  lib/providers/auth_state/implementations/auth_state_notifier_mobile.dart
  lib/providers/auth_state/implementations/auth_state_notifier_web.dart
  lib/providers/device_info.dart
  lib/providers/playback_api.dart
  lib/screens/auto_login.dart
  lib/screens/episode.dart
  lib/screens/home.dart
  lib/screens/login.dart
  lib/screens/profile/avatar.dart
  lib/screens/profile/contact_support.dart
  lib/screens/profile/profile.dart
  lib/screens/tabs_root.dart
  lib/services/share_image.dart
  pubspec.lock
  pubspec.yaml
  test/auth/auth_test.dart
  web/bccm-video-player/bccm-video-player.mjs
  web/bccm-video-player/bccm-video-player.umd.js
  web/bccm-video-player/style.css
  web/firebase-messaging-sw.js
  web/index.html
Labels: codeball:needs-careful-review

#84 Support feature tags on ListSection
  external_projects/bccm_player/example/pubspec.lock
  lib/components/episode_list_episode.dart
  lib/components/list_section.dart
  lib/screens/search/search_results_page.dart
  pubspec.lock
Labels: codeball:needs-review

#86 Refactor/cleanup main continued
  lib/app_root.dart
  lib/components/bottom_sheet_mini_player.dart
  lib/components/live_mini_player.dart
  lib/main.dart
  lib/providers/chromecast.dart
  lib/providers/playback_api.dart
  lib/providers/playback_listener.dart
  lib/providers/router_provider.dart
  lib/providers/settings.dart
  lib/providers/video_state.dart
  lib/screens/episode.dart
  lib/screens/live.dart
  lib/screens/tabs_root.dart
  lib/services/deeplink_service.dart
  lib/services/firebase.dart
  lib/services/playback_service.dart
  lib/theme/bccm_theme.dart
Labels: codeball:needs-review

#87 Feat/refactor default poster sections
  lib/components/default_section.dart
  lib/components/page.dart
  lib/components/poster_section.dart
  lib/components/sections/thumbnail/episode_thumbnail.dart
  lib/components/sections/thumbnail/show_thumbnail.dart
  lib/components/sections/thumbnail_slider/item_section_thumbnail_slider.dart
  lib/components/sections/thumbnail_slider/thumbnail_slider_episode.dart
  lib/components/sections/thumbnail_slider/thumbnail_slider_show.dart
  lib/graphql/queries/page.graphql
  lib/graphql/queries/page.graphql.dart
  lib/graphql/queries/sections.graphql.dart
  lib/graphql/schema/schema.graphql.dart
Labels: codeball:needs-careful-review

#89 Use EpisodeThumbnail for ListSection and SearchResult page
  lib/components/episode_list_episode.dart
  lib/components/page.dart
  lib/components/sections/list_section.dart
  lib/components/sections/thumbnail/episode_thumbnail.dart
  lib/components/sections/thumbnail_slider/thumbnail_slider_episode.dart
  lib/models/episode_thumbnail_data.dart
  lib/models/episode_thumbnail_data.freezed.dart
Labels: codeball:approved

#90 Create ItemSectionThumbnailGrid to support DefaultGrid and PosterGrid…
  lib/components/achievement_list.dart
  lib/components/default_grid_section.dart
  lib/components/grid_row.dart
  lib/components/icon_grid_section.dart
  lib/components/page.dart
  lib/components/poster_grid_section.dart
  lib/components/sections/thumbnail/episode_thumbnail.dart
  lib/components/sections/thumbnail/show_thumbnail.dart
  lib/components/sections/thumbnail_grid/item_section_thumbnail_grid.dart
  lib/components/sections/thumbnail_grid/thumbnail_grid.dart
  lib/components/sections/thumbnail_grid/thumbnail_grid_episode.dart
  lib/components/sections/thumbnail_grid/thumbnail_grid_show.dart
  lib/components/sections/thumbnail_slider/thumbnail_slider_show.dart
  lib/graphql/queries/page.graphql
  lib/graphql/queries/page.graphql.dart
  lib/graphql/queries/sections.graphql.dart
  lib/screens/episode.dart
Labels: codeball:needs-review

#88 Refactor/episode widgets
  .vscode/launch.json
  analysis_options.yaml
  lib/api/brunstadtv.dart
  lib/components/custom_tab_bar.dart
  lib/components/dropdown_select.dart
  lib/components/episode/episode_info.dart
  lib/components/episode/episode_related.dart
  lib/components/episode/episode_season.dart
  lib/components/episode/episode_tabs.dart
  lib/components/episode/player_error.dart
  lib/components/episode/player_poster.dart
  lib/components/episode_tab_selector.dart
  lib/components/pulse_animation.dart
  lib/components/season_episode_list.dart
  lib/components/season_episode_list.freezed.dart
  lib/components/share_episode_sheet.dart
  lib/components/study_button.dart
  lib/graphql/queries/episode.graphql
  lib/graphql/queries/episode.graphql.dart
  lib/graphql/queries/season.graphql
  lib/graphql/queries/season.graphql.dart
  lib/graphql/schema/schema.graphql.dart
  lib/helpers/navigation_utils.dart
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_bg.dart
  lib/l10n/app_localizations_da.dart
  lib/l10n/app_localizations_de.dart
  lib/l10n/app_localizations_en.dart
  lib/l10n/app_localizations_es.dart
  lib/l10n/app_localizations_fi.dart
  lib/l10n/app_localizations_fr.dart
  lib/l10n/app_localizations_hu.dart
  lib/l10n/app_localizations_it.dart
  lib/l10n/app_localizations_nb.dart
  lib/l10n/app_localizations_nl.dart
  lib/l10n/app_localizations_pl.dart
  lib/l10n/app_localizations_pt.dart
  lib/l10n/app_localizations_ro.dart
  lib/l10n/app_localizations_ru.dart
  lib/l10n/app_localizations_sl.dart
  lib/l10n/app_localizations_tr.dart
  lib/l10n/intl_en.arb
  lib/providers/analytics.dart
  lib/providers/chromecast.dart
  lib/providers/lesson_progress_provider.dart
  lib/providers/playback_listener.dart
  lib/router/router.gr.dart
  lib/screens/episode.dart
  lib/screens/live.dart
  lib/screens/study.dart
  lib/screens/tabs_root.dart
  pubspec.lock
  pubspec.yaml
Labels: codeball:needs-careful-review
