Repository bcc-code/bcc-media-app, pull requests merged in 2023-03, with the labels that each got.

#95 Send ShowID instead of the localized title to NPAW
  lib/graphql/queries/episode.graphql
  lib/graphql/queries/episode.graphql.dart
  lib/providers/playback_service.dart
Labels: codeball:needs-review

#96 Fix/deep link issues
  .maestro/flows/4_deep-links-bcc.yml
  .maestro/flows/6_notifications_stopped.yml
  .maestro/flows/subflows/home/home_ios.yml
  android/app/src/debug/AndroidManifest.xml
  external_projects/bccm_player/lib/src/playback_platform_interface.dart
  external_projects/bccm_player/lib/src/plugins/riverpod/providers/player_provider.dart
  external_projects/bccm_player/lib/src/state/player_state_notifier.dart
  external_projects/bccm_player/lib/src/state/plugin_state_notifier.dart
  external_projects/bccm_player/test/bccm_player_test.dart
  integration_test/common/init.dart
  lib/api/brunstadtv.dart
  lib/app_root.dart
  lib/components/developer_options.dart
  lib/helpers/firebase.dart
  lib/helpers/navigation/navigation_utils.dart
  lib/helpers/redirect.dart
  lib/helpers/special_routes.dart
  lib/main.dart
  lib/models/events/app_ready.dart
  lib/providers/notification_service.dart
  lib/router/router.dart
  lib/router/router.gr.dart
  lib/router/special_routes_guard.dart
  lib/screens/auto_login.dart
  lib/screens/tabs_root.dart
  pubspec.yaml
Labels: codeball:needs-review

#99 fix(bccm_player): hotfix for npaw initialization
  external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/ExoPlayerController.kt
  external_projects/bccm_player/lib/bccm_player_native.dart
  external_projects/bccm_player/lib/bccm_player_web.dart
  external_projects/bccm_player/lib/src/playback_platform_interface.dart
  external_projects/bccm_player/test/bccm_player_test.dart
  lib/main.dart
  lib/providers/playback_service.dart
Labels: codeball:needs-review

#98 Feat/survey
  lib/api/brunstadtv.dart
  lib/components/bottom_sheet_mini_player.dart
  lib/components/mini_player.dart
  lib/components/prompts/prompt_survey.dart
  lib/components/prompts/prompts.dart
  lib/components/surveys/bottom_sheet_survey.dart
  lib/components/surveys/dialog_confirm_cancel.dart
  lib/components/surveys/rating_bar.dart
  lib/components/surveys/survey_form.dart
  lib/components/surveys/survey_question_rating.dart
  lib/components/surveys/survey_question_text.dart
  lib/graphql/queries/prompts.graphql
  lib/graphql/queries/prompts.graphql.dart
  lib/graphql/schema/schema.graphql.dart
  lib/helpers/constants.dart
  lib/helpers/ui/btv_buttons.dart
  lib/helpers/ui/svg_icons.dart
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_bg.dart
  lib/l10n/app_localizations_da.dart
  lib/l10n/app_localizations_de.dart
  lib/l10n/app_localizations_en.dart
  lib/l10n/app_localizations_es.dart
  lib/l10n/app_localizations_fi.dart
  lib/l10n/app_localizations_fr.dart
  lib/l10n/app_localizations_hu.dart
  lib/l10n/app_localizations_it.dart
  lib/l10n/app_localizations_nb.dart
  lib/l10n/app_localizations_nl.dart
  lib/l10n/app_localizations_pl.dart
  lib/l10n/app_localizations_pt.dart
  lib/l10n/app_localizations_ro.dart
  lib/l10n/app_localizations_ru.dart
  lib/l10n/app_localizations_sl.dart
  lib/l10n/app_localizations_tr.dart
  lib/l10n/intl_en.arb
  lib/models/survey.dart
  lib/models/survey.freezed.dart
  lib/models/survey.g.dart
  lib/providers/prompts.dart
  lib/providers/surveys.dart
  lib/screens/profile/contact_support.dart
  lib/screens/tabs_root.dart
  lib/theme/bccm_input_decorations.dart
Labels: codeball:needs-careful-review

#100 add missing .env.template
  integration_test/env/.env.dart.template
Labels: codeball:needs-review

#101 Fix links for live episodes
  lib/components/section_item_click_wrapper.dart
  lib/components/sections/thumbnail/episode_thumbnail.dart
  lib/helpers/navigation/navigation_utils.dart
  lib/helpers/ui/ui_utils.dart
Labels: codeball:approved

#102 Feat/AnonymousUserContactSupport
  lib/screens/profile/profile.dart
Labels: codeball:needs-careful-review

#104 Feat/android language npaw
  external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/ExoPlayerController.kt
Labels: codeball:needs-review

#105 feat(npaw): Send current episode on livestream
  lib/components/episode_list_episode.dart
  lib/components/featured_section.dart
  lib/components/sections/thumbnail_grid/thumbnail_grid.dart
  lib/components/sections/thumbnail_slider/item_section_thumbnail_slider.dart
  lib/graphql/queries/calendar_episode_entries.graphql
  lib/graphql/queries/calendar_episode_entries.graphql.dart
  lib/screens/live.dart
Labels: codeball:needs-review
