Repository bcc-code/bcc-media-app, pull requests merged in 2023-04, with the labels that each got.

#103 Fix/EnableAndroidVibration
  android/app/src/main/AndroidManifest.xml
  lib/helpers/webview/main_js_channel.dart
  pubspec.yaml
Labels: codeball:needs-review

#107 Fix/back nav fullscreen
  android/app/src/main/kotlin/com/example/my_app/MainActivity.kt
  external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/FullscreenPlayerView.kt
Labels: codeball:needs-review

#108 Feat/new tag for episodes
  lib/components/season_episode_list.dart
  lib/components/sections/thumbnail/episode_thumbnail.dart
  lib/components/sections/thumbnail_slider/thumbnail_slider_episode.dart
  lib/helpers/episode_state.dart
  lib/helpers/ui/ui_utils.dart
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_bg.dart
  lib/l10n/app_localizations_da.dart
  lib/l10n/app_localizations_de.dart
  lib/l10n/app_localizations_en.dart
  lib/l10n/app_localizations_es.dart
  lib/l10n/app_localizations_fi.dart
  lib/l10n/app_localizations_fr.dart
  lib/l10n/app_localizations_hu.dart
  lib/l10n/app_localizations_it.dart
  lib/l10n/app_localizations_nb.dart
  lib/l10n/app_localizations_nl.dart
  lib/l10n/app_localizations_pl.dart
  lib/l10n/app_localizations_pt.dart
  lib/l10n/app_localizations_ro.dart
  lib/l10n/app_localizations_ru.dart
  lib/l10n/app_localizations_sl.dart
  lib/l10n/app_localizations_tr.dart
  lib/l10n/intl_en.arb
Labels: codeball:needs-careful-review

#109 Fix link for live item in featured section
  lib/components/featured_section.dart
Labels: codeball:approved

#112 fix(android): Call stop on primarycontroller when plugin is detached from activity
  external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/BccmPlayerPlugin.kt
Labels: codeball:approved

#113 fix(android): Keep playing when user locks phone
  external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/BccmPlayerPlugin.kt
  external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/BccmPlayerPluginEvent.kt
  external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/views/FullscreenPlayerView.kt
  external_projects/bccm_player/example/pubspec.lock
  external_projects/bccm_player/pubspec.yaml
  pubspec.lock
Labels: codeball:needs-review

#111 fix(player): experimental solution to force landscape on ios
  external_projects/bccm_player/ios/Classes/Players/AVQueuePlayerController.swift
  external_projects/bccm_player/ios/Classes/Utils/LandscapeAVPlayerViewController.swift
  external_projects/bccm_player/ios/Classes/Views/BccmPlayerView.swift
  ios/Runner/AppDelegate.swift
Labels: codeball:needs-review

#116 Feat/episode desc enhancement
  lib/components/episode/episode_info.dart
  lib/components/text_collapsible.dart
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_bg.dart
  lib/l10n/app_localizations_da.dart
  lib/l10n/app_localizations_de.dart
  lib/l10n/app_localizations_en.dart
  lib/l10n/app_localizations_es.dart
  lib/l10n/app_localizations_fi.dart
  lib/l10n/app_localizations_fr.dart
  lib/l10n/app_localizations_hu.dart
  lib/l10n/app_localizations_it.dart
  lib/l10n/app_localizations_nb.dart
  lib/l10n/app_localizations_nl.dart
  lib/l10n/app_localizations_pl.dart
  lib/l10n/app_localizations_pt.dart
  lib/l10n/app_localizations_ro.dart
  lib/l10n/app_localizations_ru.dart
  lib/l10n/app_localizations_sl.dart
  lib/l10n/app_localizations_tr.dart
  lib/l10n/intl_en.arb
Labels: codeball:needs-careful-review
